### PR TITLE
Youtube clone

### PR DESCRIPTION
**Pull request by MarioDena**
Israel and I finished the branch feature and validated our HTML.

We are ready for review!

### CODE REVIEW

**Review by uche-inyama — COMMENTED** [review]
## Pull request under review by Inyama, Uchechukwu Henry

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Hi team, :wave: nice job,

### But there are changes that you need to effect.

- [ ] You missed the search button, the search button should be at the end (rightmost part) of the search bar
- [ ] There are no linter checks on this project. I looked at your master branch I can see you have a .stickler.yml file and also, that your master branch is 3 commits ahead of your feature branch. My question is, did you create the stickler file in your master branch after you created and committed to your feature branch? If so you have to push to your feature branch to add the file you left behind.

- [ ] There should be at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar, but you have only one. You can use [Font awesome](https://fontawesome.com/) for better icons.

### After implementing these changes submit another form for code review.

### This project is not approved :stop_sign:

**Comment by MarioDena** [comment]
Hello @uche-inyama , Can you change the list of changes needed to be made? The project instructions states we should not add linter checks yet, Please refer to the instructions. 

The linter files were added when we installed the linter checks for the second project.

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
Good job TEAM, 👋👋👋👋
you are a step away from completing this project. There is one rectification to be done before we proceed to the next project.
- ### **[REQUIRED]** 
The project must show the avatar of the user who uploaded the video( there should be an avatar/image of the one who uploaded the video like the youtube page)
quickly fix this and submit for review.🙂🙂🙂
 *** [optional]
> Please do well to stick to the scope of the project. The project is supposed to be implemented by HTML and CSS. Try as much as possible to do that in the next project.

#### Happy coding👋👋👋👋

**Comment by uche-inyama** [comment]
> Hello @uche-inyama , Can you change the list of changes needed to be made? The project instructions states we should not add linter checks yet, Please refer to the instructions.
> 
> The linter files were added when we installed the linter checks for the second project.

Hi team, you are right . Passing linter check is not a requirement for this project to be approved, apologies :pray:  :slightly_smiling_face:

**Comment by MarioDena** [comment]
@Forison ???????? Im sorry but we do have an image showing the avatar... Can you please double check? 
We will change the avatar to another image and resubmit but I ask you with all due respect that you refer to the project instructions more closely.

**Review by uche-inyama — APPROVED** [review]
## Hi @MarioDena  & @Israel-Laguan,  :wave: 

### Your project is approved :heavy_check_mark: 

### Go ahead and merge to master branch  :slightly_smiling_face:

**Comment by Israel-Laguan** [comment]
> 
> ## Hi @MarioDena & @Israel-Laguan, wave
> ### Your project is approved heavy_check_mark
> ### Go ahead and merge to master branch slightly_smiling_face

Hey really appreciated! Thanks!

**Pull request merged**
