### PR TITLE
change image depends on the contents

### PR DESCRIPTION
**Pull request by mdrianislam0or1**
Issue title: Change Image - Microverse-Basic-HTML-Proyect-One
Change Image
change-img

### CODE REVIEW

**Comment by Israel-Laguan** [comment]
I think in this case something related to youtube, as the site itself is a clone of youtube

**Review by Israel-Laguan — APPROVED** [review]

**Review by e-azocar — APPROVED** [review]

**Comment by e-azocar** [comment]
@Israel-Laguan could I mark this issue as done?

**Comment by Israel-Laguan** [comment]
> @Israel-Laguan could I mark this issue as done?

I think QA should see it somehow

**Review by angelik0828 — APPROVED** [review]

**Pull request merged**
